name: Build Documentation

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: pip install mkdocs-material
      - name: Set up git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy docs
        run: mkdocs gh-deploy --force
